### ISSUE TITLE
Error generating SQL query.

### ISSUE THREAD

**Issue by Akai-Abd** [suhaybkaofficial/sqltalk#1]
Generating Natural Language Query getting error. [ https://www.dsoft.cloudns.org ]

[Error generating SQL query. Please try again.]
![PostgreSQL](https://github.com/user-attachments/assets/b62ff253-5a3b-4a0c-9de5-df5993283989)
![MySQL](https://github.com/user-attachments/assets/955c4218-c9eb-4543-bc37-352d62ae7bac)

But if i generate Natural Language Query [ https://sqltalk.vercel.app/ ] there is no any errors.
![sqltalk postgr](https://github.com/user-attachments/assets/99d0a403-8298-4615-9c32-d76a0187d1cd)
![sqltalk post](https://github.com/user-attachments/assets/7cfea042-c75a-457e-a211-3d083ba95c1c)

so please solve this issue

**Comment by suhaybkaofficial** [comment]
![Screenshot from 2024-10-12 20-53-47](https://github.com/user-attachments/assets/2dfee3d8-b66d-4673-8cda-5e5bedec88f0)

put your gemini api key in the .env.local 

you can get your own API key from here https://aistudio.google.com/app/apikey

**Comment by suhaybkaofficial** [comment]
home that helps
